### ISSUE TITLE
Defer Updates

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#1]
Can get the kDrawingDeferUpdateDesignTrackingProperties to read fine but for the life of me I can't seem to alter it in any way yet.

**Comment by AlexFielder** [comment]
Performing a search for "kDrawingDeferUpdateDesignTrackingProperties" inside of the API documentation you can see:

> "Programmatic changes to the "Defer Updates" setting made through the kDrawingDeferUpdateDesignTrackingProperties iProperty of a drawing document opened in Autodesk Inventor **will not affect the open drawing document** and **will be overwritten upon save of that document**. However, changes to the "Defer Updates" setting made through the DrawingSettings.DeferUpdates property of the API, or through the Autodesk Inventor Document Settings dialog, will be honored for the open drawing document. When opening non-Inventor DWG files, this method honors the application option to decide between open and import."

If I understand that correctly, you ought be modifying the DrawingSettings.DeferUpdates property instead.

**Comment by the-war-horse** [comment]
Darn it. That was my original code. Will fix and test this next week.

**Comment by AlexFielder** [comment]
You mean you had DrawingSettings.DeferUpdates in your iLogic already?

That is part of the reason I suggested the "change something and test" mantra yesterday. Sometimes it's a case of "Change **ONE** thing and test"; other times you can add a whole new method and then test.

**Comment by the-war-horse** [comment]
No i had it in my code to begin with but thought it was the wrong argument to send so put the k word in there instead.

**Comment by the-war-horse** [comment]
Got the code working, in latest commit.
