### ISSUE TITLE
Every file IsModifiable

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#10]
So I've added the IsModifiable = True in there but it seems that the add-in thinks that every file I open is modifiable even when they're not... I don't get it.

**Comment by AlexFielder** [comment]
Fixed this with the latest commit.

Please test it with Vault in the morning since I only set a couple of files to readonly using windows properties.

**Comment by the-war-horse** [comment]
Working. Man that was a simple thing to fix.

I was going down a route of madness...

found this, [LINK](http://adndevblog.typepad.com/manufacturing/2013/06/checkout-checkin-a-file-in-vault-2014.html)

and was trying to figure out how i could implement the code within 

`If oFileIteration.IsCheckedOut = True Then`

**Comment by AlexFielder** [comment]
You *shouldn't* be able to query your vault at all being that it is Vault basic version.

**Comment by the-war-horse** [comment]
Ahh I see... Though I still might try it haha!

Just need to play with the code a bit as a lot of it wasn't happy.

But that's not for today.

**Comment by AlexFielder** [comment]
I'll admit I've never tried to do it with Vault Basic; I would be **very** surprised if it was only hidden away just because Autodesk say it is - to encourage customers to upgrade to a paid-for version...

**Comment by the-war-horse** [comment]
True however out of all of the things I would upgrade to a paid-for version I didn't even know that this was in the pile, as I would imagine most inventor/vault users wouldn't know. So perhaps Autodesk just keep it on the quiet haha... Least this is my hope.

**Comment by the-war-horse** [comment]
Working now and updated slightly so that it updates when file is checked in or out too.
