### ISSUE TITLE
OnChangeSelect Mass Properties Update is breaking mating commands

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#13]
when running joint/Constrain commands when you hit apply the addin then fires non OnChangeSelect which in turn fires the command to update mass properties. This then breaks the running command. Need to add in some form of check that if in another command or specific commands don't run OnChangeSelect sub... Or something similar.

**Comment by AlexFielder** [comment]
That speaks volumes as to why this kind of "Live updating iProperties" hasn't happened before now...

**Comment by the-war-horse** [comment]
I think you could be right.

I'm trying to add a line that looks for

AddinGlobal.InventorApp.CommandManager.ControlDefinitions.Item("AppGroundPlaneToggleCmd")

as that seems to be the command it's struggling with right now. But I'm not sure how to do it.

it didn't like looking for it as

`If AddinGlobal.InventorApp.CommandManager.ControlDefinitions.Item("AppGroundPlaneToggleCmd").Execute() = False Then
`
or

`If AddinGlobal.InventorApp.CommandManager.ControlDefinitions.Item("AppGroundPlaneToggleCmd") = False Then`

So atm I'm going to test

`If AddinGlobal.InventorApp.CommandManager.ControlDefinitions.Item("AppGroundPlaneToggleCmd") Is Nothing Then`

but I'm not convinced it'll work.

**Comment by AlexFielder** [comment]
I'm having trouble recreating this bug; can you record a screencast showing the steps you take to produce it?

**Comment by the-war-horse** [comment]
[Screencast link](http://autode.sk/2mjVSz7)

the first time i hit the joint command it does nothing, i have to hit it twice, then when i hit apply it cancels out.

Mating with constrain works perfectly though, but again on first time hitting command button it does nothing. might have to remove the update mass properties command and see what happens.

**Comment by AlexFielder** [comment]
Hmm, that's odd.

It's working normally for me here.

**Comment by the-war-horse** [comment]
maybe I need to completely delete everything and pull it back down again?

**Comment by AlexFielder** [comment]
When you run the Joint/Constraint commands do you run them with this button ticked?
![2017-03-20 09_45_59-autodesk inventor professional 2017 - assembly2 iam](https://cloud.githubusercontent.com/assets/167413/24094833/3d1e8126-0d52-11e7-8030-3458b4d79efd.png)

**Comment by AlexFielder** [comment]
(Was just thinking that it might be to blame...)

**Comment by the-war-horse** [comment]
No I don't have that ticked.

**Comment by the-war-horse** [comment]
OK so I've cleaned everything, removed the add-in folder and reinstalled it. But it's still doing it! WTF!!!

**Comment by AlexFielder** [comment]
Have you tried setting break points (F9) at or around the location (in code) where it is erroring?

Can you post here an image of the addins you currently have loaded in Inventor? <- I'll make sure I have the same or fewer.

**Comment by the-war-horse** [comment]
i've not done breakpoints yet. trying to actually do some modelling work today which is why this is even more annoying! Will try to find bugs in a min.

**Comment by the-war-horse** [comment]
Are you running the latest commit build?

**Comment by AlexFielder** [comment]
Pretty sure I am, yes.

**Comment by the-war-horse** [comment]
![image](https://cloud.githubusercontent.com/assets/4579234/24095486/580d6ef4-0d55-11e7-86a2-779c1775f9cb.png)
![image](https://cloud.githubusercontent.com/assets/4579234/24095495/67ff89c8-0d55-11e7-9533-13ee958a5ec9.png)

**Comment by AlexFielder** [comment]
What's the blocked addin in the list above?

**Comment by the-war-horse** [comment]
no idea actually...

**Comment by AlexFielder** [comment]
select it and it will show you what path the addin is loading from in the box below the main list. Might be part of the issue...?

**Comment by the-war-horse** [comment]
doesn't show any path when selected....

**Comment by the-war-horse** [comment]
found it, deleted it!

**Comment by AlexFielder** [comment]
try running our addin again then, this time setting break points in the area that you think is causing the issue; also worth checking the log file we've been creating:

"C:\Logs\RollingFileLog.txt"

I've been a bit lax in adding debugging - I'll throw in some Try Catch Blocks around the UpdateDisplayediProperties method and a few other areas and then I must crack on...

**Comment by the-war-horse** [comment]
Hah! It's still friggin' there! Must be hiding somewhere else as well

**Comment by the-war-horse** [comment]
what's InvChronicalInventor addin?

**Comment by AlexFielder** [comment]
Screencast.

**Comment by the-war-horse** [comment]
ok cool

**Comment by AlexFielder** [comment]
Chronicle is it's original name; they let it be either by accident or realised that changing it after release will mean it gets left behind (like we found...)

**Comment by the-war-horse** [comment]
yeh.

OK so I couldn't get breakpoints to work nicely seeing as the breakpoint I'm asking for fired constantly!

I commented out the line

`'AddinGlobal.InventorApp.CommandManager.ControlDefinitions.Item("AppUpdateMassPropertiesCmd").Execute()`

and my issue goes away. So it was definitely being caused by that command being run all the time.

**Comment by the-war-horse** [comment]
commented it out in standardaddinserver that is

**Comment by AlexFielder** [comment]
Was that on line 151 or line 310? (or both)

**Comment by AlexFielder** [comment]
The trick with breakpoints is to put it at the point that it becomes useful:

![2017-03-20 10_46_11-myfirstinventoraddin - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/167413/24096715/add23d24-0d5a-11e7-8ef0-64f7fd571b60.png)

Whereas:

![2017-03-20 10_47_16-myfirstinventoraddin - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/167413/24096721/b40b6562-0d5a-11e7-90fd-223d8dcc2c08.png)

Is more directed/targeted. :-)

**Comment by the-war-horse** [comment]
commented it out on 310. the whole sub at m_StyleEvents_OnActivateStyle does nothing at all atm....

Will try some breakpoints at lunch but commenting that line definitely fixes it. It's the fact it's calling that command in the middle of another that's cancelling out the important one. Not sure why it's fine on yours though....

**Comment by AlexFielder** [comment]
"Welcome to the Jungle" that is software development...

What works on one system may not work on anything else; you have Windows 10 I think whereas I have Windows 7 (here in the office) - I have Windows 10 at home so can test it later to see if I get the same behaviour

**Comment by the-war-horse** [comment]
I have windows 10 here.

Who knows what's up...

Also... Where do the logs save again??

**Comment by the-war-horse** [comment]
Going to close this now as it's been fine since turning pre-select highlighting off.
