### ISSUE TITLE
Dia and Degree symbol not working correctly in description....

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#15]
The symbols add as expected in the Engineer textbox (4) but for some reason with exactly the same code they don't get placed where they should in the Description textbox (2).... Can't fathom it!

**Comment by AlexFielder** [comment]
{Thinking-out-loud}:
Perhaps the Description textbox is multiline?

Can you post an image showing what you mean?

**Comment by the-war-horse** [comment]
Oooooh, I think I might know what it is now... think I made the description one scrollable... But it didn't actually change it so will tweak and see....

**Comment by the-war-horse** [comment]
![image](https://cloud.githubusercontent.com/assets/4579234/24652343/66b70048-1929-11e7-9043-2235e0b16e46.png)

**Comment by the-war-horse** [comment]
Tweak made no difference..

The dia symbol was meant to go in-front of the 16mm part in both text box's. Working perfectly in the Engineer one, but not Description? Weird.

Also the cursor is supposed to focus back in to the textbox after the symbol but that's not working in either case.

**Comment by AlexFielder** [comment]
Take a look at this screenshot:
![2017-04-04 11_57_06-myfirstinventoraddin - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/167413/24653549/224385bc-192e-11e7-8fb7-b545de44faaa.png)

This is what happens when copy-pasting code. ;-)

**Comment by AlexFielder** [comment]
'Tis a subtle difference but hard to spot when looking at it if you don't set a break point at the start of each method and watch what the properties are doing.

**Comment by the-war-horse** [comment]
rats, I had made this mistake before and fixed it but I reverted the code so must have put the mistake back!

**Comment by the-war-horse** [comment]
FIXED... Just the focus issue to work out now.....

**Comment by the-war-horse** [comment]
`TextBox4.SelectionStart = insertPos + insertText.Length`

doesn't seem to work at all!

**Comment by AlexFielder** [comment]
When I'm testing things out, rather than revert if it doesn't work I'll quite-often comment out the scratchings and commit them anyway in case I want to revisit later on.

**Comment by AlexFielder** [comment]
take another look at the image above; I had only focused on the one bit that was "broken" - the whole of Button9_Click points to the wrong textbox.

**Comment by AlexFielder** [comment]
unless it's just switched of course.

It might be worth renaming the textboxes on the userform to show what they actually contain, i.e: TextBox4 becomes "tbDescription" or something similar.

**Comment by the-war-horse** [comment]
Yeh I fixed that bit. The focus stays with the button rather then going back to the textbox where it should.

**Comment by the-war-horse** [comment]
Yeh I've thought about this actually. Might be better

**Comment by AlexFielder** [comment]
using the "defaults" provided by Visual Studio is fine until such times as code starts getting copied around like this.

Speaking of which, there might be a way to halve the number of methods required for these button clicks..

**Comment by the-war-horse** [comment]
how so?

**Comment by AlexFielder** [comment]
like this:

```VB
Private Sub Button9_Click(sender As Object, e As EventArgs) Handles Button9.Click, Button8.Click
```
"Handles" accepts multiple inputs by simply adding a comma and then the next event to handle.

**Comment by AlexFielder** [comment]
from here:

https://msdn.microsoft.com/en-us/library/3exstx90(v=vs.110).aspx

**Comment by the-war-horse** [comment]
ahhhhh!!! Nice one

**Comment by AlexFielder** [comment]
If you do do that it's going to be really important (I think) to rename the textboxes appropriately otherwise you could get all kinds of confused,

**Comment by the-war-horse** [comment]
I'll have a look at figuring out how I might be able to do this in a bit then....

First need to look at the code to focus the cursor in the textbox after it inputs the symbol.

**Comment by the-war-horse** [comment]
happy with this now so closing as an issue....
