### ISSUE TITLE
Form doesn't display correct buttons when switching between parts and drawings

### ISSUE THREAD

**Issue by AlexFielder** [AlexFielder/MyFirstInventorAddin#16]
Basically:

If you have a part file open and switch to an open drawing the Sheet Material & Sheet Scale buttons stay put.

It's not until you switch to an assembly file that they correctly disappear.

Suspect that this is simply an addition to the ActivateDocument event handler.

**Comment by the-war-horse** [comment]
Bug isn't showing my end... Or at least I can't seem to replicate it.
