### ISSUE TITLE
When placing component in an assembly command cancels out on it's own.

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#18]
It doesn't seem to matter if it's placing a content centre part or a part from your computer/vault but when you're in the place command, find your part then hit OK, a lot of times it will simply do nothing. Cancels out of the command. I think it could be related to OnActivateView event but not totally sure.

Question is..... Is there a way to have the rest of the code 'Do Nothing whilst a place component or Mate component command is active???

**Comment by AlexFielder** [comment]
Latest set of commits seems to have prevented this happening; at least, I couldn't force it to do it when I tried earlier.
