### ISSUE TITLE
Read model info in drawing

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#3]
Trying to get something similar to what I have already.

Aim to show Material in part or assembly and be able to edit it.

Also want to be able to show and potentially edit part material within drawing.

think I need to implement something like...
UCase(iProperties.Material(modelName))

Not sure how yet. Investigation needed.

Successfully able to read material but would like to do more with it.

**Comment by AlexFielder** [comment]
You would probably only want the Material (to display) inside of an assembly if we worked out how to display iProperty values inside of our form when you select a sub-part I guess?

To do that we would need to tie into the DocumentEvents.OnChangeSelectSet event which fires when you change a selection inside of an Assembly document.

By the way, when you get to it, there's an "Event Watcher" tool provided by Autodesk that allows you to see what events happen inside of Inventor when you perform certain actions.

The path to the 2017 version is: 

"C:\Users\Public\Documents\Autodesk\Inventor 2017\SDK\DeveloperTools\Tools\EventWatcher\bin\Release\EventWatcher.exe"

If you run that when Inventor is open, and select (for instance) the DocumentEvents.OnChangeSelectSet tick box with an assembly document open which contains sub-components, when you click on one of the sub-components (for instance a part) it produces the following:

DocumentEvents.OnChangeSelectSet
     Context: No context information
     BeforeOrAfter: kAfter
     HandlingCode: Uknown type specified.
     Select set is empty.
**DocumentEvents.OnChangeSelectSet
     Context: No context information
     BeforeOrAfter: kAfter
     HandlingCode: Uknown type specified.
     Select set contents:
                   ComponentOccurrence**
DocumentEvents.OnChangeSelectSet
     Context: No context information
     BeforeOrAfter: kAfter
     HandlingCode: Uknown type specified.
     Select set is empty.

The key part here is highlighted in bold; the object we care about in this case would be ComponentOccurrence - from which we can read and set iProperty values.

**Comment by the-war-horse** [comment]
Very interesting!

I've managed to get the creation date in there a little sweeter using datetimepicker.

I'll have to look in to this event watcher. That could prove very useful indeed.

Cheers.

**Comment by the-war-horse** [comment]
OK so I'm still struggling with this one.

Trying to play with the idea of being able to see the material and mass of the part/assembly in a drawing. But so far I'm at a loss how to get the properties which are easily displayable on the drawing itself to show in the addin.

It seems equally as hard to show material in an assembly. And still struggling with being able to implement material changes from the addin. I think its probably beyond me tbh. I recon I can get the material to update when components are selected. Maybe even the mass too actually. But other then that I don't know.

tried code similar to this...

myiPropsForm.TextBox8.Text = AddinGlobal.InventorApp.PartDocument.PropertySets.Item("Design Tracking Properties").Item("Mass").Value

but it's not right. Not happy with either PartDocument or ModelDocument and I couldn't even get it working with DocumentTypeEnum.kPartDocumentObject. I just don't know.

**Comment by AlexFielder** [comment]
Instead of: 
```VB
myiPropsForm.TextBox8.Text = AddinGlobal.InventorApp.PartDocument.PropertySets.Item("Design Tracking Properties").Item("Mass").Value
```
try it with:

```VB
myiPropsForm.TextBox8.Text = AddinGlobal.InventorApp.Activedocument.PropertySets.Item("Design Tracking Properties").Item("Mass").Value`
```
and see what happens.

Aside from that I would need to put aside some time to delve into exactly how you would achieve the Material change from within the Addin itself.

In order to pull/change the currently selected material from/to a selected part occurrence I suspect you would need to grab the underlying PartDocument, read in the material list in much the same way you did in iLogic before adding an UpdatePartMaterial() method that runs when you click the update button.

In Pseudo code I suspect you would need to do something like this to get the occurrence part document:

```VB
'psuedo-code follows but should mostly work
'************************
'get a selection set from an assembly
'you could check that the selectset only contains one occurrence
Dim occurrenceList As New Collection
Dim entity As Object
For Each entity In assemblydoc.SelectSet
    If TypeOf entity Is ComponentOccurrence Then
        occurrenceList.Add(entity)
    End If
Next

If occurrenceList.Count < 1 Then
    MsgBox("At least one occurrence must be selected.")
    Exit Sub
End If
'************************
'work on occurrences
For Each occ as ComponentOccurrence In occurrenceList 'there should be only one
    If occ.DefinitionDocumentType = DocumentTypeEnum.kPartDocumentObject Then
        Dim tmpPart As PartDocument = occ.definition.Document
        'Access available part materials list as per iLogic or:
        'build a list of available materials:
        dim materialList as List(Of MaterialAsset) = new List(Of MaterialAsset)
        For each partMat as MaterialAsset in tmpPart.MaterialAssets
                materialList.add(partMat)
        next
        'add contents of materialList to the Userform
        For i = 0 to materialList.count
                MyForm.Combobox1.add(materialList.item(i).Name)                
        next
    Else
        Throw New NotImplementedException
    End If
Next
```

Accessing components is *relatively* easy once you realise they are simply "copies" of the original document. :)

**Comment by AlexFielder** [comment]
FWIW: The above only gets the available materials from the currently selected part occurrence. To set the material after clicking the update button you would need to compare the Combobox.Selectedtext string with the list of available materials and when there's a match set it to that.

**Comment by the-war-horse** [comment]
ok that's cool thanks.

I will have a better look at this code in a bit.

Just out of interest what does adding the ' to the end of value do?

**Comment by the-war-horse** [comment]
Could I pull parts from this code to use within.

m_DocumentEvents_OnChangeSelectSet

so that it updates the addin info with that of the currently selected part? That would be amazing to have.

maybe using

 If AddinGlobal.InventorApp.ActiveDocument Is ComponentOccurrence then

and then perhaps would this work for each of the properties in the addin?

iProperties.GetorSetStandardiProperty(AddinGlobal.InventorApp.ActiveDocument.ComponentOccurrence, PropertiesForDesignTrackingPropertiesEnum.kPartNumberDesignTrackingProperties, "", "")

**Comment by AlexFielder** [comment]
That last suggestion won't work at all - the compiler will tell you as such*.

OnChangeSelectSet might help, but you need to get to grips with parsing through the assembly structure. Then this will all fall into place.

*It should, but then again, it is Microsoft after all... ;-)

**Comment by the-war-horse** [comment]
Ok cool thanks. I'll try to get my head around it some more and it might make sense.

**Comment by the-war-horse** [comment]
Wondering if something like 

OnChangeSelect.ComponentDefinition might work within this solution?

Similar to the Button3_Click code?

so something like this maybe?

```
Dim oCompDef As ComponentDefinition
            oCompDef = OnChangeSelect.ComponentDefinition.Item
```

**Comment by the-war-horse** [comment]
I've ma managed to get this working now so closing!
