### ISSUE TITLE
iProperty fields not quite working

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#4]
In new file, part file for example. If you edit description and hit update button it does nothing. Once you save the file the box reverts back to what it was before edited. However now when you update description and hit update the change sticks and pushes to iproperties.

**Comment by AlexFielder** [comment]
That is by design, the Part Number isn't written until the file is saved; I'm not sure you can even access the other iProperties until then.

**Comment by the-war-horse** [comment]
I dunno. I can set the properties by using an ilogic form or by going in to iproperties. There's​ gotta be a way. Just need to find it.

**Comment by the-war-horse** [comment]
This is the part in event watcher that happens when i update the iproperties in a new part or use my iLogic form to change it.

DocumentEvents.OnChangeSelectSet
     Context: No context information
     BeforeOrAfter: kAfter
     HandlingCode: Uknown type specified.
     Select set contents:
                   PartComponentDefinition
UserInputEvents.OnContextMenu
     SelectionDevice: kBrowserSelection
     AdditionalInfo: Nothing
     CommandBar: Menu (CommandBar)
     Context is Nothing
UserInputEvents.OnActivateCommand
     CommandName: "PartiPropertiesCmd"
     Context: No context information
TransactionEvents.OnCommit
     TransactionObject: Properties (Transaction)
     Context: No context information
     BeforeOrAfter: kBefore
     HandlingCode: kEventHandled
TransactionEvents.OnCommit
     TransactionObject: Properties (Transaction)
     Context: No context information
     BeforeOrAfter: kAfter
     HandlingCode: kEventHandled

It's the TransactionEvents.OnCommit part that triggers right when hit apply but I'm not sure if that's the issue. It doesn't actually push the data from the addin to iproperties to apply it in the first place. So i need to figure out how to try and get that working first.

**Comment by AlexFielder** [comment]
I wouldn't worry too much about the TransactionEvents.OnCommit() too much.

In user terms, when you activate a command such as the PartiPropertiesCmd above, you are actually starting a transaction which is the mechanism that allows the user to perform an Undo if they wish.

The following shows a simple transaction:
```VB
Private Shared Sub GeneratePyramid(pyramidheight As String)
    Dim height As Integer = Convert.ToInt32(pyramidheight)
    Dim rowCount As Integer = 1
    Dim spacing As Double = 10 'units = cm
    Dim oPartDocument As PartDocument = g_inventorApplication.ActiveDocument
    Dim oCompDef As PartComponentDefinition = oPartDocument.ComponentDefinition
    Dim oTrans As TransientGeometry = g_inventorApplication.TransientGeometry

    Dim trans As Transaction = g_inventorApplication.TransactionManager.StartTransaction(oPartDocument, "Create pyramid of points")

    'Dim partOrigin As Point = oTrans.CreatePoint(0, 0, 0)

    'i = row
    'j = column
    Dim XSpacing As Double = 0
    Dim YSpacing As Double = 0
    Dim ZSpacing As Double = 0
    For i As Integer = height To 0 Step -1
        'Dim tmpPoint As Point = g_inventorApplication.TransientGeometry.CreatePoint(0, 0, 0)


        For j As Integer = 1 To i
            Dim wp As WorkPoint = oCompDef.WorkPoints.AddFixed(oTrans.CreatePoint(XSpacing, YSpacing, ZSpacing))
            'set up X Spacing
            XSpacing += spacing
        Next

        'For j As Integer = 1 To rowCount
        YSpacing += spacing
        XSpacing = (spacing * rowCount) / 2
        'Next
        rowCount += 1
    Next

    trans.End()
End Sub
```

**Comment by the-war-horse** [comment]
OK, thanks.

For now I don't think it can be done but I'm still hunting.

**Comment by AlexFielder** [comment]
Thinking about it, I suppose you could have the Update button save the file if isn't saved already, and as we already have:

```VB
Private Sub m_ApplicationEvents_OnSaveDocument(DocumentObject As _Document, 
                                                       BeforeOrAfter As EventTimingEnum, 
                                                       Context As NameValueMap, 
                                                       ByRef HandlingCode As HandlingCodeEnum)
    If BeforeOrAfter = EventTimingEnum.kAfter Then
        UpdateDisplayediProperties()
    End If
    HandlingCode = HandlingCodeEnum.kEventNotHandled
End Sub
```

It's not difficult to modify it to take account of the EventTimingEnum.Before enum in order to make sure that properties have been updated prior to saving the file:

```VB
Private Sub m_ApplicationEvents_OnSaveDocument(DocumentObject As _Document, 
                                                       BeforeOrAfter As EventTimingEnum, 
                                                       Context As NameValueMap, 
                                                       ByRef HandlingCode As HandlingCodeEnum)
    If BeforeOrAfter = EventTimingEnum.kBefore Then
        UpdateiPropertiesWithDisplayedValues()
    End If
    If BeforeOrAfter = EventTimingEnum.kAfter Then
        UpdateDisplayediProperties()
    End If
    HandlingCode = HandlingCodeEnum.kEventNotHandled
End Sub
```

You could even go so far as to **prevent** or perhaps delay initial saving of a file unless it has specific properties filled out.

**Comment by the-war-horse** [comment]
OK this I like the look of. I'll try this out later on if I get a chance.

I'm not getting much work done today because I keep playing with code etc... :s oops....

**Comment by AlexFielder** [comment]
It's a slippery slope certainly...

Probably best if you set aside an hour a day during work hours to look at things.

At least until you can go to your boss and say "look what I created off the back of the training; imagine what I could do with more..."

And then come back to us for some more training. ;-)

**Comment by the-war-horse** [comment]
Haha, you never know!

I've always loved coding (or atleast the idea of it) and have played a lot over the years with scripts and such for windows, proe, android etc. I wish I could fully understand the actual code so I could do more. But I doubt it'll be something my work will help with. I think I might have to do more personal training on it though. Still have some Enhanced Learning Credits to use.

**Comment by AlexFielder** [comment]
I was going to recommend a book to you last week and I realised yesterday that there aren't any that I have seen for Visual Basic .NET - that are < 10 years old at least.

The best books I have ever bought for this sort of thing were: 

http://shop.oreilly.com/product/9780596159849.do

& (most recently):

https://www.amazon.co.uk/Programming-6-0-Windows-Desktop-Applications/dp/1491922192

I realise neither of these are VB-specific, but the theory is that if you can write VB.NET then you can relatively easily write C#.NET.

**Comment by the-war-horse** [comment]
Awesome thank you.

I was looking at a course in java but that's something different again. But I was thinking if it helped me get my head around coding in general it might be useful.

**Comment by the-war-horse** [comment]
Closing this as it's just not possible to do certain things before saving a file
