### ISSUE TITLE
Fields default value

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#5]
In the addin fields. Stock Number, Engineer etc. They have a default value in their boxes. This seems harmless unless you want one of these to be left blank. The problem is that once you save the file or hit update in the addin etc it pushes the values in the boxes to iproperties. Even if you delete it out it comes back. Need to work out how to show these as blank. Or write a rule that states, IF TextBox2.Text = Description then TextBox2.Text = " "

Not sure if this will work since it'll be fighting with itself then.

**Comment by AlexFielder** [comment]
I suppose a quick fix would be to wrap the parts of the UpdateDisplayediProperties() method that matter in a check for whether the file has been saved or not:

If inventorApp.ActiveDocument.FullFileName?.Length > 0 Then
'Do something
End If

If it hasn't then do as you suggested and blank out those textbox.text values.

**Comment by the-war-horse** [comment]
Fixed issue by added code in the UpdateDisplayediProperties() method as you suggested but also in the TextBox#_Leave methods as well so that it always checks to see what's in the boxes and if the default values are in there it'll send blacks to iproperties.

Will commit shortly
