### ISSUE TITLE
trying to get #ITEM button to work from addin

### ISSUE THREAD

**Issue by the-war-horse** [AlexFielder/MyFirstInventorAddin#6]
This code works up until the last line where it fails. Need to figure out how to create custom property and write variable to it.

`Dim doc = inventorApp.ActiveDocument
        Dim oAssyDef As AssemblyComponentDefinition = doc.ComponentDefinition
        Dim oBOM As BOM = oAssyDef.BOM

        oBOM.StructuredViewEnabled = True

        Dim oBOMView As BOMView = oBOM.BOMViews.Item("Structured")

        Dim oBOMRow As BOMRow

        For Each oBOMRow In oBOMView.BOMRows
            'Set a reference to the primary ComponentDefinition of the row
            Dim oCompDef As ComponentDefinition
            oCompDef = oBOMRow.ComponentDefinitions.Item(1)

            Dim CompFullDocumentName As String = oCompDef.Document.FullDocumentName
            Dim CompFileNameOnly As String
            Dim index As Integer = CompFullDocumentName.LastIndexOf("\")

            CompFileNameOnly = CompFullDocumentName.Substring(index + 1)

            'MessageBox.Show(CompFileNameOnly)

            Dim item As String
            item = oBOMRow.ItemNumber

            'inventorApp.ActiveDocument.PropertySets.Item("Inventor User Defined Properties").Item(CompFileNameOnly).Item("#ITEM").Value = item
            inventorApp.ActiveDocument.PropertySets.value(CompFileNameOnly, "Custom", "#ITEM") = item
        Next`

**Comment by the-war-horse** [comment]
origional last line code from iLogic was

iProperties.value(CompFileNameOnly, "Custom", "#ITEM") = item

**Comment by AlexFielder** [comment]
You might have missed it since I didn't cover it on Thursday last, but there's an iProperties.SetorCreateCustomiProperty() method that can help with this:

```VB
Function SetorCreateCustomiProperty(ByVal Doc As Inventor.Document, ByVal PropertyName As String, Optional ByVal PropertyValue As Object = Nothing) As Object
' Get the custom property set.
Dim customPropSet As Inventor.PropertySet
Dim customproperty As Object = Nothing

customPropSet = Doc.PropertySets.Item("Inventor User Defined Properties")

' Get the existing property, if it exists.
Dim prop As Inventor.Property = Nothing
Dim propExists As Boolean = True
Try
    prop = customPropSet.Item(PropertyName)
Catch ex As Exception
    propExists = False
End Try
If Not PropertyValue Is Nothing Then
    ' Check to see if the property was successfully obtained.
    If Not propExists Then
        ' Failed to get the existing property so create a new one.
        prop = customPropSet.Add(PropertyValue, PropertyName)
    Else
        ' Change the value of the existing property.
        prop.Value = PropertyValue
    End If
Else
    customproperty = prop.Value
End If
Return customproperty
End Function
```

**Comment by AlexFielder** [comment]
Used like this:
```VB
iProperties.SetorCreateCustomiProperty(ActiveDoc, "Vault Category", Parameters.GetParameter("VaultCategory"))
```

**Comment by the-war-horse** [comment]
OK. this could be very very handy!

Do you think I could use this like this;

`    oBOM.StructuredViewEnabled = True

    Dim oBOMView As BOMView = oBOM.BOMViews.Item("Structured")

    Dim oBOMRow As BOMRow

    For Each oBOMRow In oBOMView.BOMRows
        'Set a reference to the primary ComponentDefinition of the row
        Dim oCompDef As ComponentDefinition
        oCompDef = oBOMRow.ComponentDefinitions.Item(1)

        Dim CompFullDocumentName As String = oCompDef.Document.FullDocumentName
        Dim CompFileNameOnly As String
        Dim index As Integer = CompFullDocumentName.LastIndexOf("\")

        CompFileNameOnly = CompFullDocumentName.Substring(index + 1)

        'MessageBox.Show(CompFileNameOnly)

        Dim item As String
        item = oBOMRow.ItemNumber

       iProperties.SetorCreateCustomiProperty(CompFileName, item, Parameters.GetParameter("#ITEM"))
    Next``

**Comment by the-war-horse** [comment]
oops think i need it the other way around.

iProperties.SetorCreateCustomiProperty(CompFileName, "#ITEM", Parameters.GetParameter(item))

**Comment by AlexFielder** [comment]
Err, no.

You need to pass it an Inventor.Document (any document type is okay I think), a property name & if you are adding or changing the property value a string value is required.

This #Item iProperty was to do with having sub-parts match the parent assembly parts list, correct?

**Comment by AlexFielder** [comment]
That's not to say you couldn't modify it if you wanted to. ;-)

**Comment by the-war-horse** [comment]
Yes this is to have a custom iproperty in each part within an assembly called #ITEM which is a copy of the items Item Number within the assembly BOM. It's really useful. I also looked at it because it access's the parts within an assembly I wondered if I could tweak the code for other things. But I don't think it's able to do what I'd like.

Might have to try and modify the function and perhaps create a new one that can set custom property of a file within an assembly. Will see what I can achieve.

**Comment by AlexFielder** [comment]
If you need me to look at the parts-in-assemblies thing I can; just submit what you've done already and I'll add to it where I can.

You have to remember that inside of an Assembly you have to first access the componentoccurrence and then get the document property for it.

The psuedo-code I posted in the other issue thread shows you how.

**Comment by the-war-horse** [comment]
TBH I've removed everything I've done so far. I'll have another go tomorrow and if I can get anywhere I'll commit it and maybe we'll get somewhere.

I'm struggling with accessing the componentoccurrence part, need to look closer at the code you posted because I can't wrap my head around it atm.

**Comment by AlexFielder** [comment]
Have a search inside of the API Help for componentoccurrence - there are a bunch of samples provided.

Failing that, searching for the same thing inside [my iLogic repo](https://github.com/AlexFielder/iLogic/search?utf8=%E2%9C%93&q=componentoccurrence) returns 19 results.

**Comment by the-war-horse** [comment]
OK didn't think of that. Really need to utilise that API help more haha.

Thanks.

**Comment by AlexFielder** [comment]
It really is a big help (and then sometimes **no help at all**, but let's not go there unless we have to)

**Comment by the-war-horse** [comment]
I always tend to simply Google everything from the off. But it's not always useful.

**Comment by the-war-horse** [comment]
All Working. Hoping to be able to use some of the code to read info of parts within assemblies and drawings now too.
