### ISSUE TITLE
Try to reduce duplication where possible/logical

### ISSUE THREAD

**Issue by AlexFielder** [AlexFielder/MyFirstInventorAddin#7]
I have noticed there are quite a few checks for the same thing: 

```VB
If AddinGlobal.InventorApp.ActiveDocument.DocumentType = 
DocumentTypeEnum.kPartDocumentObject Then
```
appears several times, as does this:
```VB
If AddinGlobal.InventorApp.ActiveDocument.DocumentType =
DocumentTypeEnum.kDrawingDocumentObject Then
```

Unless there's a "chicken & egg" scenario, I would recommend combining these checks together. It will make the code easier to read and there will be less of it.

**Comment by the-war-horse** [comment]
Should I do this with Dims?

Something like

```
Dim PartDoc = (AddinGlobal.InventorApp.ActiveDocument.DocumentType = DocumentTypeEnum.kPartDocumentObject)
Dim DrawDoc = (AddinGlobal.InventorApp.ActiveDocument.DocumentType =
DocumentTypeEnum.kDrawingDocumentObject)
```

then

`If PartDoc Then`... etc etc...

Or will that not work?

**Comment by AlexFielder** [comment]
No, I only did that because these comment windows are a fixed width and if the line is too long it screws up the readability of things.

**Comment by AlexFielder** [comment]
What I was referring to was this sort of thing:

![2017-03-15 11_14_06-myfirstinventoraddin - microsoft visual studio administrator](https://cloud.githubusercontent.com/assets/167413/23946051/c432bbcc-0970-11e7-8b80-f533e31bd8a4.png)

The drawing documentType is checked for 4 times in quick succession.

**Comment by the-war-horse** [comment]
Ahhhhhh

Now I'm with you!!

OK yes, I'll sort that out.

**Comment by the-war-horse** [comment]
Code cleaned up
