### ISSUE TITLE
Form broken on loading with no file active

### ISSUE THREAD

**Issue by AlexFielder** [AlexFielder/MyFirstInventorAddin#9]
I don't think this is supposed to happen:

![2017-03-15 14_05_12-autodesk inventor professional 2017](https://cloud.githubusercontent.com/assets/167413/23952217/9c411bf0-0988-11e7-8d47-e0750e8dcb67.png)

**Comment by AlexFielder** [comment]
Also broken for parts:
![2017-03-15 14_21_29-autodesk inventor professional 2017](https://cloud.githubusercontent.com/assets/167413/23952881/cb691a84-098a-11e7-9c08-a95accc8c149.png)

**Comment by the-war-horse** [comment]
Yes i think I've fixed it now. But my comp just died so restarting again. Will push commit soon.

**Comment by the-war-horse** [comment]
Fixed. Though unfortunately it still looks ugly on first boot of inventor when no file is open.
